export const careerData = [
    {
      category: 'Agriculture & Food',
      image: '/images/agriculture.jpg',
      careers: [
        {
          id: 'farmer',
          title: 'Farmer',
          description: 'Manage farms and grow crops or raise livestock.',
          salary: '$40,000 - $80,000/year',
          education: 'Experience or Agriculture Degree',
          outlook: 'Stable demand',
        },
        {
          id: 'food-scientist',
          title: 'Food Scientist',
          description: 'Research ways to improve food safety and production.',
          salary: '$60,000 - $100,000/year',
          education: "Bachelor's Degree in Food Science",
          outlook: 'Growing field',
        },
      ],
    },
    {
      category: 'Arts',
      image: '/images/arts.jpg',
      careers: [
        {
          id: 'graphic-designer',
          title: 'Graphic Designer',
          description: 'Create visual concepts to communicate ideas.',
          salary: '$45,000 - $80,000/year',
          education: "Bachelor's Degree in Graphic Design or related field",
          outlook: 'Steady growth',
        },
        {
          id: 'illustrator',
          title: 'Illustrator',
          description: 'Create images for books, magazines, and digital media.',
          salary: '$40,000 - $75,000/year',
          education: "Bachelor's Degree in Fine Arts or Illustration",
          outlook: 'Niche but steady demand',
        },
      ],
    },
    {
      category: 'Aviation',
      image: '/images/aviation.jpg',
      careers: [
        {
          id: 'pilot',
          title: 'Pilot',
          description: 'Fly airplanes and helicopters to transport people and goods.',
          salary: '$80,000 - $180,000/year',
          education: 'Commercial Pilot License',
          outlook: 'High demand, especially regional pilots',
        },
        {
          id: 'air-traffic-controller',
          title: 'Air Traffic Controller',
          description: 'Coordinate aircraft to ensure safe takeoff and landing.',
          salary: '$90,000 - $150,000/year',
          education: 'Specialized Training + FAA Certification',
          outlook: 'Competitive but strong',
        },
      ],
    },
    {
      category: 'Education',
      image: '/images/education.jpg',
      careers: [
        {
          id: 'teacher',
          title: 'Teacher',
          description: 'Instruct students in schools at various levels.',
          salary: '$45,000 - $75,000/year',
          education: "Bachelor's Degree in Education",
          outlook: 'Steady growth',
        },
        {
          id: 'education-administrator',
          title: 'Education Administrator',
          description: 'Manage operations of educational institutions.',
          salary: '$70,000 - $120,000/year',
          education: "Master's Degree in Education Leadership or related field",
          outlook: 'Growing demand',
        },
      ],
    },
    {
      category: 'Engineering',
      image: '/images/engineering.jpg',
      careers: [
        {
          id: 'civil-engineer',
          title: 'Civil Engineer',
          description: 'Design and oversee construction projects like roads and bridges.',
          salary: '$70,000 - $115,000/year',
          education: "Bachelor's Degree in Civil Engineering",
          outlook: 'Faster than average growth',
        },
        {
          id: 'mechanical-engineer',
          title: 'Mechanical Engineer',
          description: 'Develop and test mechanical devices, including tools and engines.',
          salary: '$75,000 - $120,000/year',
          education: "Bachelor's Degree in Mechanical Engineering",
          outlook: 'Strong steady demand',
        },
      ],
    },
    {
      category: 'Finance',
      image: '/images/finance.jpg',
      careers: [
        {
          id: 'accountant',
          title: 'Accountant',
          description: 'Prepare and examine financial records.',
          salary: '$55,000 - $90,000/year',
          education: "Bachelor's Degree in Accounting",
          outlook: 'Steady demand',
        },
        {
          id: 'financial-analyst',
          title: 'Financial Analyst',
          description: 'Advise businesses and individuals on investments.',
          salary: '$65,000 - $110,000/year',
          education: "Bachelor's Degree in Finance or Business",
          outlook: 'Strong demand',
        },
      ],
    },
    {
      category: 'Hospitality & Tourism',
      image: '/images/hospitality.jpg',
      careers: [
        {
          id: 'hotel-manager',
          title: 'Hotel Manager',
          description: 'Oversee hotel operations and guest services.',
          salary: '$50,000 - $90,000/year',
          education: "Bachelor's Degree in Hospitality Management",
          outlook: 'Growing travel industry',
        },
        {
          id: 'travel-agent',
          title: 'Travel Agent',
          description: 'Plan and book trips and vacations for clients.',
          salary: '$35,000 - $60,000/year',
          education: 'Certificate or Associate Degree',
          outlook: 'Evolving into luxury travel specialization',
        },
      ],
    },
    {
      category: 'Law & Government',
      image: '/images/law.jpg',
      careers: [
        {
          id: 'lawyer',
          title: 'Lawyer',
          description: 'Represent clients in legal disputes and provide legal advice.',
          salary: '$90,000 - $160,000/year',
          education: "Juris Doctor (JD) Degree",
          outlook: 'Steady demand',
        },
        {
          id: 'police-officer',
          title: 'Police Officer',
          description: 'Protect public safety and enforce laws.',
          salary: '$45,000 - $80,000/year',
          education: 'High school diploma and police academy training',
          outlook: 'Steady demand',
        },
      ],
    },
    {
      category: 'Logistics & Supply Chain',
      image: '/images/logistics.jpg',
      careers: [
        {
          id: 'logistics-coordinator',
          title: 'Logistics Coordinator',
          description: 'Manage the supply chain and flow of goods.',
          salary: '$50,000 - $85,000/year',
          education: "Bachelor's Degree in Supply Chain Management",
          outlook: 'Strong and growing',
        },
        {
          id: 'warehouse-manager',
          title: 'Warehouse Manager',
          description: 'Oversee warehouse operations and staff.',
          salary: '$45,000 - $80,000/year',
          education: 'Experience or Business Degree',
          outlook: 'High demand with e-commerce boom',
        },
      ],
    },
    {
      category: 'Media',
      image: '/images/media.jpg',
      careers: [
        {
          id: 'journalist',
          title: 'Journalist',
          description: 'Research, write, and present news stories.',
          salary: '$40,000 - $80,000/year',
          education: "Bachelor's Degree in Journalism or Communications",
          outlook: 'Declining but niche strong areas',
        },
        {
          id: 'content-creator',
          title: 'Content Creator',
          description: 'Produce engaging online content for audiences.',
          salary: '$35,000 - $75,000/year',
          education: 'Self-taught or degree in Media, Communications',
          outlook: 'Rapidly expanding field',
        },
      ],
    },
    {
      category: 'Medical',
      image: '/images/medical.jpg',
      careers: [
        {
          id: 'registered-nurse',
          title: 'Registered Nurse',
          description: 'Provide direct patient care and support.',
          salary: '$65,000 - $100,000/year',
          education: "Associate's or Bachelor's Degree in Nursing",
          outlook: 'Much faster than average growth',
        },
        {
          id: 'physical-therapist',
          title: 'Physical Therapist',
          description: 'Help patients recover and improve mobility.',
          salary: '$75,000 - $110,000/year',
          education: "Doctorate of Physical Therapy (DPT)",
          outlook: 'Faster than average growth',
        },
      ],
    },
    {
      category: 'Military & Protective Services',
      image: '/images/military.jpg',
      careers: [
        {
          id: 'soldier',
          title: 'Soldier',
          description: 'Serve and protect the nation in armed forces.',
          salary: '$30,000 - $80,000/year',
          education: 'High School + Military Training',
          outlook: 'Always needed',
        },
        {
          id: 'firefighter',
          title: 'Firefighter',
          description: 'Respond to fires and emergencies to save lives.',
          salary: '$40,000 - $75,000/year',
          education: 'Fire Academy Training',
          outlook: 'Strong demand',
        },
      ],
    },
    {
      category: 'Science',
      image: '/images/science.jpg',
      careers: [
        {
          id: 'chemist',
          title: 'Chemist',
          description: 'Study substances to understand and improve products and processes.',
          salary: '$60,000 - $100,000/year',
          education: "Bachelor's or Master's Degree in Chemistry",
          outlook: 'Stable growth',
        },
        {
          id: 'biologist',
          title: 'Biologist',
          description: 'Research organisms and their environments.',
          salary: '$50,000 - $90,000/year',
          education: "Bachelor's or Master's Degree in Biology",
          outlook: 'Steady growth',
        },
      ],
    },
    {
      category: 'Skilled Trades',
      image: '/images/trades.jpg',
      careers: [
        {
          id: 'electrician',
          title: 'Electrician',
          description: 'Install and maintain electrical systems in homes and businesses.',
          salary: '$50,000 - $85,000/year',
          education: 'Trade School or Apprenticeship',
          outlook: 'High demand',
        },
        {
          id: 'plumber',
          title: 'Plumber',
          description: 'Install and repair piping systems.',
          salary: '$50,000 - $80,000/year',
          education: 'Trade School or Apprenticeship',
          outlook: 'Very strong demand',
        },
      ],
    },
    {
      category: 'Tech',
      image: '/images/tech.jpg',
      careers: [
        {
          id: 'software-developer',
          title: 'Software Developer',
          description: 'Design and build computer applications to solve user problems.',
          salary: '$80,000 - $120,000/year',
          education: "Bachelor's Degree in Computer Science or related field",
          outlook: 'Much faster than average growth',
        },
        {
          id: 'data-scientist',
          title: 'Data Scientist',
          description: 'Analyze complex data to help organizations make better decisions.',
          salary: '$90,000 - $140,000/year',
          education: "Bachelor's or Master's Degree in Data Science or Statistics",
          outlook: 'High demand, strong growth',
        },
        {
          id: 'cybersecurity-analyst',
          title: 'Cybersecurity Analyst',
          description: 'Protect systems and networks from digital threats.',
          salary: '$85,000 - $130,000/year',
          education: "Bachelor's Degree in Cybersecurity or Information Technology",
          outlook: 'Extremely high demand',
        },
      ],
    },
  ];
  